// USERS
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const LOGOUT = "LOGOUT";

// POSTS
export const SET_POST = "SET_POST";
export const SET_POSTS = "SET_POSTS";
export const FETCH_POST = "FETCH_POST";
export const FETCH_POSTS = "FETCH_POSTS";
export const SUBMITTING_POST = "SUBMITTING_POST";
export const LOADING_POST = "LOADING_POST";
export const LOADING_POSTS = "LOADING_POSTS";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POSTS = "UPDATE_POSTS";


// COMMENTS
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";